# Step 0.0. Install LightAutoML 

Uncomment if doesn't clone repository by git. (ex.: colab, kaggle version)

In [1]:
#! pip install -U lightautoml

# Step 0.1. Import necessary libraries 

In [2]:
# Standard python libraries
import os
import time
import requests
# Installed libraries
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import torch

# Imports from our package
import gensim
from lightautoml.automl.presets.tabular_presets import TabularAutoML, TabularUtilizedAutoML
from lightautoml.dataset.roles import DatetimeRole
from lightautoml.tasks import Task

# Step 0.2. Parameters 

In [3]:
N_THREADS = 8 # threads cnt for lgbm and linear models
N_FOLDS = 5 # folds cnt for AutoML
RANDOM_STATE = 42 # fixed random state for various reasons
TEST_SIZE = 0.2 # Test size for metric check
TIMEOUT = 300 # Time in seconds for automl run
TARGET_NAME = 'TARGET' # Target column name

# Step 0.3. Fix torch number of threads and numpy seed 

In [4]:
np.random.seed(RANDOM_STATE)
torch.set_num_threads(N_THREADS)

# Step 0.4. Example data load 

Load a dataset from the repository if doesn't clone repository by git.

In [5]:
DATASET_DIR = '../data/'
DATASET_NAME = 'sampled_app_train.csv'
DATASET_FULLNAME = os.path.join(DATASET_DIR, DATASET_NAME)
DATASET_URL = 'https://raw.githubusercontent.com/sberbank-ai-lab/LightAutoML/master/examples/data/sampled_app_train.csv'

In [6]:
%%time

if not os.path.exists(DATASET_FULLNAME):
    os.makedirs(DATASET_DIR, exist_ok=True)

    dataset = requests.get(DATASET_URL).text
    with open(DATASET_FULLNAME, 'w') as output:
        output.write(dataset)

CPU times: user 115 µs, sys: 31 µs, total: 146 µs
Wall time: 117 µs


In [7]:
%%time

data = pd.read_csv(DATASET_FULLNAME)
data.head()

CPU times: user 116 ms, sys: 7.88 ms, total: 124 ms
Wall time: 124 ms


SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      313802       0         Cash loans           M            N   
1      319656       0         Cash loans           F            N   
2      207678       0    Revolving loans           F            Y   
3      381593       0         Cash loans           F            N   
4      258153       0         Cash loans           F            Y   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          270000.0    327024.0      15372.0   
1               N             0          108000.0    675000.0      19737.0   
2               Y             2          112500.0    270000.0      13500.0   
3               N             1           67500.0    142200.0       9630.0   
4               Y             0          337500.0   1483231.5      46570.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         0.0                        0.0   
4                         0.0                        2.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         1.0  
3                        0.0                         4.0  
4                        0.0                         0.0  

[5 rows x 122 columns]

# Step 0.5. (Optional) Some user feature preparation 

Cell below shows some user feature preparations to create task more difficult (this block can be omitted if you don't want to change the initial data):

In [8]:
%%time

data['BIRTH_DATE'] = (np.datetime64('2018-01-01') + data['DAYS_BIRTH'].astype(np.dtype('timedelta64[D]'))).astype(str)
data['EMP_DATE'] = (np.datetime64('2018-01-01') + np.clip(data['DAYS_EMPLOYED'], None, 0).astype(np.dtype('timedelta64[D]'))
                    ).astype(str)

data['constant'] = 1
data['allnan'] = np.nan

data['report_dt'] = np.datetime64('2018-01-01')

data.drop(['DAYS_BIRTH', 'DAYS_EMPLOYED'], axis=1, inplace=True)

CPU times: user 129 ms, sys: 0 ns, total: 129 ms
Wall time: 132 ms


# Step 0.6. (Optional) Data splitting for train-test 

Block below can be omitted if you are going to train model only or you have specific train and test files:

In [9]:
%%time

train_data, test_data = train_test_split(data, 
                                         test_size=TEST_SIZE, 
                                         stratify=data[TARGET_NAME], 
                                         random_state=RANDOM_STATE)
print('Data splitted. Parts sizes: train_data = {}, test_data = {}'
              .format(train_data.shape, test_data.shape))

Data splitted. Parts sizes: train_data = (8000, 125), test_data = (2000, 125)
CPU times: user 10.6 ms, sys: 0 ns, total: 10.6 ms
Wall time: 10.2 ms


In [10]:
train_data.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
6444      112261       0         Cash loans           F            N   
3586      115058       0         Cash loans           F            N   
9349      326623       0         Cash loans           F            N   
7734      191976       0         Cash loans           M            Y   
2174      281519       0    Revolving loans           F            N   

     FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
6444               N             1           90000.0    640080.0      31261.5   
3586               Y             0          180000.0    239850.0      23850.0   
9349               Y             0          112500.0    337500.0      31086.0   
7734               Y             1           67500.0    135000.0       9018.0   
2174               Y             0           67500.0    202500.0      10125.0   

      ...  AMT_REQ_CREDIT_BUREAU_DAY AMT_REQ_CREDIT_BUREAU_WEEK  \
6444  ...                        0.0                        0.0   
3586  ...                        0.0                        0.0   
9349  ...                        0.0                        0.0   
7734  ...                        NaN                        NaN   
2174  ...                        0.0                        0.0   

     AMT_REQ_CREDIT_BUREAU_MON AMT_REQ_CREDIT_BUREAU_QRT  \
6444                       0.0                       1.0   
3586                       0.0                       0.0   
9349                       0.0                       0.0   
7734                       NaN                       NaN   
2174                       0.0                       0.0   

     AMT_REQ_CREDIT_BUREAU_YEAR  BIRTH_DATE    EMP_DATE  constant  allnan  \
6444                        0.0  1985-06-28  2012-06-21         1     NaN   
3586                        3.0  1953-12-27  2018-01-01         1     NaN   
9349                        2.0  1975-06-21  2016-06-17         1     NaN   
7734                        NaN  1988-04-27  2009-06-05         1     NaN   
2174                        2.0  1975-06-13  1997-01-22         1     NaN   

      report_dt  
6444 2018-01-01  
3586 2018-01-01  
9349 2018-01-01  
7734 2018-01-01  
2174 2018-01-01  

[5 rows x 125 columns]

# Step 0.7. (Optional) Reading data from SqlDataSource

### Preparing datasets as SQLite data bases

In [11]:
import sqlite3 as sql

for _fname in ('train.db', 'test.db'):
    if os.path.exists(_fname):
        os.remove(_fname)
    
train_db = sql.connect('train.db')
train_data.to_sql('data', train_db)

test_db = sql.connect('test.db')
test_data.to_sql('data', test_db)

### Using dataset wrapper for a connection

In [12]:
from lightautoml.reader.tabular_batch_generator import SqlDataSource

# train_data is replaced with a wrapper for an SQLAlchemy connection
# Wrapper requires SQLAlchemy connection string and query to obtain data from
train_data = SqlDataSource('sqlite:///train.db', 'select * from data', index='index')
test_data = SqlDataSource('sqlite:///test.db', 'select * from data', index='index')

# ========= AutoML preset usage =========


## Step 1. Create Task

In [13]:
%%time

task = Task('binary', )

CPU times: user 2.7 ms, sys: 577 µs, total: 3.28 ms
Wall time: 3.04 ms


## Step 2. Setup columns roles

Roles setup here set target column and base date, which is used to calculate date differences:

In [14]:
%%time

roles = {'target': TARGET_NAME,
         DatetimeRole(base_date=True, seasonality=(), base_feats=False): 'report_dt',
         }

CPU times: user 26 µs, sys: 6 µs, total: 32 µs
Wall time: 35.5 µs


## Step 3. Create AutoML from preset

To create AutoML model here we use `TabularAutoML` preset, which looks like:

![TabularAutoML preset pipeline](../imgs/tutorial_2_pipeline.png)

All params we set above can be send inside preset to change its configuration:

In [15]:
%%time 

automl = TabularAutoML(task = task, 
                       timeout = TIMEOUT,
                       general_params = {'nested_cv': False, 'use_algos': [['linear_l2', 'lgb', 'lgb_tuned']]},
                       reader_params = {'cv': N_FOLDS, 'random_state': RANDOM_STATE},
                       tuning_params = {'max_tuning_iter': 20, 'max_tuning_time': 30},
                       lgb_params = {'default_params': {'num_threads': N_THREADS}})
oof_pred = automl.fit_predict(train_data, roles = roles)
print('oof_pred:\n{}\nShape = {}'.format(oof_pred, oof_pred.shape))

oof_pred:
array([[0.03176575],
       [0.02935533],
       [0.02988034],
       ...,
       [0.02417618],
       [0.18293583],
       [0.09939367]], dtype=float32)
Shape = (8000, 1)
CPU times: user 4min 17s, sys: 1.61 s, total: 4min 19s
Wall time: 1min 13s


## Step 4. Predict to test data and check scores

In [16]:
%%time

test_pred = automl.predict(test_data)
print('Prediction for test data:\n{}\nShape = {}'
              .format(test_pred, test_pred.shape))

print('Check scores...')
print('OOF score: {}'.format(roc_auc_score(train_data.data[TARGET_NAME].values, oof_pred.data[:, 0])))
print('TEST score: {}'.format(roc_auc_score(test_data.data[TARGET_NAME].values, test_pred.data[:, 0])))

Prediction for test data:
array([[0.07546484],
       [0.08182896],
       [0.03427348],
       ...,
       [0.06038745],
       [0.04366009],
       [0.20293215]], dtype=float32)
Shape = (2000, 1)
Check scores...
OOF score: 0.7443675471901889
TEST score: 0.7320040760869565
CPU times: user 1.2 s, sys: 7.92 ms, total: 1.21 s
Wall time: 644 ms


## Step 5. Create AutoML with time utilization 

Below we are going to create specific AutoML preset for TIMEOUT utilization (try to spend it as much as possible):

In [17]:
%%time 

automl = TabularUtilizedAutoML(task = task, 
                       timeout = TIMEOUT,
                       general_params = {'nested_cv': False, 'use_algos': [['linear_l2', 'lgb', 'lgb_tuned']]},
                       reader_params = {'cv': N_FOLDS, 'random_state': RANDOM_STATE},
                       tuning_params = {'max_tuning_iter': 20, 'max_tuning_time': 30},
                       lgb_params = {'default_params': {'num_threads': N_THREADS}})
oof_pred = automl.fit_predict(train_data, roles = roles)
print('oof_pred:\n{}\nShape = {}'.format(oof_pred, oof_pred.shape))

oof_pred:
array([[0.03556265],
       [0.04054436],
       [0.03493924],
       ...,
       [0.02597675],
       [0.17027435],
       [0.10953236]], dtype=float32)
Shape = (8000, 1)
CPU times: user 14min 52s, sys: 4.59 s, total: 14min 57s
Wall time: 4min 2s


## Step 6. Predict to test data and check scores for utilized automl

In [18]:
%%time

test_pred = automl.predict(test_data)
print('Prediction for test data:\n{}\nShape = {}'
              .format(test_pred, test_pred.shape))

print('Check scores...')
print('OOF score: {}'.format(roc_auc_score(train_data.data[TARGET_NAME].values, oof_pred.data[:, 0])))
print('TEST score: {}'.format(roc_auc_score(test_data.data[TARGET_NAME].values, test_pred.data[:, 0])))

Prediction for test data:
array([[0.06939968],
       [0.08968934],
       [0.03309563],
       ...,
       [0.05409869],
       [0.04045196],
       [0.21078698]], dtype=float32)
Shape = (2000, 1)
Check scores...
OOF score: 0.7518295785065265
TEST score: 0.7328362771739131
CPU times: user 3.35 s, sys: 0 ns, total: 3.35 s
Wall time: 1.41 s
